In [1]:
import pandas as pd

In [2]:
output_sorted = pd.read_csv('test/sorted_output.csv')

# contar o quanstas vezes cada linha diferente aparece
output_sorted['count'] = 1
output_sorted = output_sorted.groupby(['ID_a_m', 'ID_b_M', 'ID\'', 'a_m', 'b_M', 'f']).sum().reset_index()

# filtrar as linhas com count maior que 1
output_sorted = output_sorted[output_sorted['count'] > 1].reset_index(drop=True)

# sort by 'f' descending
output_sorted = output_sorted.sort_values(by='f', ascending=True).reset_index(drop=True)

output_sorted

   ID_a_m ID_b_M    ID'       a_m       b_M         f  count
0   APQFW  APQFW  APQFW  0.531606  0.039280  0.000436     80
1   QXWPQ  QXWPQ  QXWPQ  0.755581  0.051939  0.001540    104
2   QHFFB  QHFFB  QHFFB  0.520210  0.078232  0.001656    352
3   CEHCH  CEHCH  CEHCH  0.997799  0.054058  0.002909     12
4   VTRRB  VTRRB  VTRRB  0.906804  0.103171  0.008753    120
5   QTBXI  QTBXI  QTBXI  0.447034  0.226107  0.010217    920
6   HCDAR  HCDAR  HCDAR  0.768230  0.277775  0.045537    576
7   RELLN  RELLN  RELLN  0.850920  0.266666  0.051489    352
8   SJYBL  SJYBL  SJYBL  0.524287  0.493583  0.066967   1428
9   ZJKPQ  ZJKPQ  ZJKPQ  0.579430  0.452576  0.068768   1216
10  PTNSN  PTNSN  PTNSN  0.684445  0.383188  0.068786    896
11  HNWNK  HNWNK  HNWNK  0.829201  0.330337  0.075030    572
12  LRBBM  LRBBM  LRBBM  0.840188  0.394383  0.109797    540
13  WHSQM  WHSQM  WHSQM  0.588640  0.657304  0.149704   1656
14  OPKMC  OPKMC  OPKMC  0.738534  0.639979  0.223394   1120
15  FSBCN  FSBCN  FSBCN  0.732654  0.656564  0.231394   1320
16  YNECD  YNECD  YNECD  0.949327  0.525995  0.249342    360
17  IVSWM  IVSWM  IVSWM  0.881062  0.641081  0.319035    588
18  RJXKI  RJXKI  RJXKI  0.992228  0.576971  0.327741    152
19  KICQC  KICQC  KICQC  0.983596  0.666880  0.430258    288

In [3]:
output_sorted1 = pd.read_csv('sorted_output.csv')
output_sorted1

   ID_a_m ID_b_M    ID'       a_m       b_M         f  numTimes
0   APQFW  APQFW  APQFW  0.531606  0.039280  0.000436         0
1   QXWPQ  GXXPK  QXWPQ  0.755581  0.020023  0.000594         0
2   QXWPQ  QXWPQ  QXWPQ  0.755581  0.051939  0.001540         0
3   QHFFB  QHFFB  QHFFB  0.520210  0.078232  0.001656        12
4   CEHCH  CEHCH  CEHCH  0.997799  0.054058  0.002909         0
5   VTRRB  VTRRB  VTRRB  0.906804  0.103171  0.008753         9
6   QTBXI  QTBXI  QTBXI  0.447034  0.226107  0.010217        60
7   HCDAR  HCDAR  HCDAR  0.768230  0.277775  0.045537       132
8   JMOWF  JMOWF  JMOWF  0.998925  0.218257  0.047534         0
9   RELLN  RELLN  RELLN  0.850920  0.266666  0.051489        40
10  SJYBL  SJYBL  SJYBL  0.524287  0.493583  0.066967       221
11  ZJKPQ  ZJKPQ  ZJKPQ  0.579430  0.452576  0.068768         0
12  PTNSN  PTNSN  PTNSN  0.684445  0.383188  0.068786        30
13  HNWNK  HNWNK  HNWNK  0.829201  0.330337  0.075030        42
14  LRBBM  LRBBM  LRBBM  0.840188  0.394383  0.109797       135
15  WHSQM  WHSQM  WHSQM  0.588640  0.657304  0.149704       120
16  OPKMC  OPKMC  OPKMC  0.738534  0.639979  0.223394        88
17  FSBCN  FSBCN  FSBCN  0.732654  0.656564  0.231394        30
18  YNECD  YNECD  YNECD  0.949327  0.525995  0.249342        39
19  IVSWM  IVSWM  IVSWM  0.881062  0.641081  0.319035        40
20  RJXKI  RJXKI  RJXKI  0.992228  0.576971  0.327741         0
21  KICQC  KICQC  KICQC  0.983596  0.666880  0.430258         0